version: '3'
services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/app.conf:/etc/nginx/conf.d/app.conf
  app:
    image: ghcr.io/tiago970/app-test:latest

