name: "Build image"

on: 
  push:
    branches:
      - main
    paths:
      - './app/**'
      - './Dockerfile'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io/tiago970

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Hash
      run: echo {{ github.sha }} | cut -c1-10

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUBTOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest, ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
