name: "yaml lint"

on: 
  push:
    paths:
      - '**.yml'
      - '**.yaml'

jobs:
  lintAllyamls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lint
        uses: ibiqlik/action-yamllint@v3
